name: Docker Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: shopping
          push: true
          tags: sudhinsuresh9526/shopping-web-django:tagname
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Create a temporary SSH key file
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # SSH into EC2 instance and deploy
          ssh -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            # Pull the latest Docker image
            docker pull sudhinsuresh9526/shopping-web-django:tagname

            # Stop and remove the existing container (if any)
            docker stop shopping-web || true
            docker rm shopping-web || true

            # Run the new Docker container
            docker run -d --name shopping-web -p 8000:8000 sudhinsuresh9526/shopping-web-django:tagname
          EOF

          # Clean up the temporary SSH key file
          rm private_key.pem
