name: Deploy Django Application

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t sudhinsuresh9526/shopping-web-django:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push sudhinsuresh9526/shopping-web-django:latest

    # Optional: Deploy to server if needed
    # Uncomment and configure the following steps if you have a deployment process
    # - name: SSH to server and deploy
    #   uses: appleboy/ssh-action@v0.1.1
    #   with:
    #     host: ${{ secrets.SERVER_IP }}
    #     username: ${{ secrets.SERVER_USER }}
    #     key: ${{ secrets.SERVER_SSH_KEY }}
    #     script: |
    #       docker pull sudhinsuresh9526/shopping-web-django:latest
    #       docker-compose -f /path/to/docker-compose.yml up -d
