name: Deploy Django Application

on:
  push:
    branches:
      - main  # Adjust if you use a different branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust based on your Python version

    - name: Install SSH client
      run: sudo apt-get install openssh-client

    - name: Add SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@your_server_ip << 'EOF'
        cd /DjangoEcommerceShopping/shopping
        git pull origin main
        docker-compose down
        docker-compose up -d --build
        EOF
