name: Deploy Django Application

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem

      - name: Deploy to EC2
        env:
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_HOST_DNS: ${{ secrets.EC2_HOST_DNS }}
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem $EC2_USERNAME@$EC2_HOST_DNS << 'EOF'
            # Navigate to your project directory
            cd /DjangoEcommerceShopping/shopping
            
            # Pull the latest changes from the repository
            git pull origin main
            
            # Activate virtual environment
            source DjangoEcommerceShopping/ven/bin/activate
            
            # Install any new dependencies
            pip install -r requirements.txt
            
            # Apply database migrations
            python manage.py migrate
            
            # Collect static files
            python manage.py collectstatic --noinput
            
            # Restart the application server
            sudo systemctl restart gunicorn
            
            # If you're using Nginx, you may want to reload it as well
            sudo systemctl reload nginx
          EOF
